# templates/ci.yml.j2

name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        # platforms ← array of runner labels, e.g. ["macos-14","ubuntu-24.04"]
        os: [ macos-latest ]
        # build types ← typically ["Release"], but extensible
        build_type: [ Release ]


    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: src

      - name: Pre-build Command make update
        run: |
          cd src
          make update

      - name: Configure
        run: |
          cmake \
            -S src -B build -GNinja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
            -DCMAKE_INSTALL_RPATH=@loader_path/../Resources/lib


      - name: Build
        run: cmake --build build --parallel

      - name: Inspect RPATHs
        run: |
          otool -l build/bin/Blender.app/Contents/MacOS/Blender \
            | grep -A2 LC_RPATH || echo "no RPATHs found"

      - name: Test
        run: |
          ctest --test-dir build --output-on-failure


